### ISSUE TITLE
Crash when attempting to descend ladder

### ISSUE THREAD

**Issue by hkhalil-akamai** [Andy-Guti/pythonTBG#21]
Received the option to "Take the plunge". Taking it resulted in the following crash:

```
Traceback (most recent call last):
  File "/Users/hkhalil/Documents/PythonTBG/Main.py", line 288, in <module>
    startGame = main()
                ^^^^^^
  File "/Users/hkhalil/Documents/PythonTBG/Main.py", line 285, in main
    curses.wrapper(Main)
  File "/opt/homebrew/Cellar/python@3.12/3.12.7/Frameworks/Python.framework/Versions/3.12/lib/python3.12/curses/__init__.py", line 94, in wrapper
    return func(stdscr, *args, **kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hkhalil/Documents/PythonTBG/Main.py", line 224, in Main
    game.new_floor()
  File "/Users/hkhalil/Documents/PythonTBG/Engine.py", line 271, in new_floor
    self.current_option.explored = True
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'int' object has no attribute 'explored'
```

**Comment by Andy-Guti** [comment]
Linked PR should fix the issue! Thanks for reporting this!!!!!
