### ISSUE TITLE
dev branch fails

### ISSUE THREAD

**Issue by kutlay** [Andy-Guti/pythonTBG#22]
```
akutlay@bos-mpcp5 pythonTBG % git checkout dev
error: pathspec 'dev' did not match any file(s) known to git
akutlay@bos-mpcp5 pythonTBG % git checkout development
M	__pycache__/Engine.cpython-311.pyc
M	__pycache__/Objects.cpython-311.pyc
branch 'development' set up to track 'origin/development'.
Switched to a new branch 'development'
akutlay@bos-mpcp5 pythonTBG % python3 Main.py
Traceback (most recent call last):
  File "/Users/akutlay/game/pythonTBG/Main.py", line 288, in <module>
    startGame = main()
                ^^^^^^
  File "/Users/akutlay/game/pythonTBG/Main.py", line 285, in main
    curses.wrapper(Main)
  File "/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/curses/__init__.py", line 94, in wrapper
    return func(stdscr, *args, **kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/akutlay/game/pythonTBG/Main.py", line 224, in Main
    game.new_floor()
  File "/Users/akutlay/game/pythonTBG/Engine.py", line 271, in new_floor
    self.current_option.explored = True
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'int' object has no attribute 'explored'
```

**Comment by kutlay** [comment]
jk my bad there is an issue for it
